dist: xenial

language: rust

rust:
  - stable

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libraw-dev libtiff-dev libjpeg-dev libopenjp2-7-dev libgif-dev libpng-dev libwebp-dev